# Начало работы

In [267]:
import numpy as np
debug_print = False

In [268]:
def qr(A_orig: np.matrix) -> tuple[np.matrix, np.matrix]:
    """
    QR метод через матрицы отражения

    Args:
        A (np.matrix): Матрица A

    Returns:
        (Q, R) (tuple[np.matrix, np.matrix]): Матрицы Q и R

    """
    
    
    
    n = A_orig.shape[0]
    Q = np.eye(n)
    
    A = A_orig.copy()
    
    for k in range(n - 1):
        # Вычисление нормали
        p = np.zeros((n, 1))
        a_kk = A[k, k]
        if a_kk != 0:
            a_kk_n = (1 if a_kk >= 0 else -1) * np.sqrt(sum(elem ** 2 for elem in A[k:, k]))
            
        else:
            a_kk_n = np.sqrt(2)
            
        p[k] = a_kk + a_kk_n
        p[k+1:] = A[k+1:, k]
        
        # print(np.eye(n) - p * p.T, "ss")
        
        P = np.eye(n) - 2 / float(sum(p[l] * p[l] for l in range(n))) * p * p.T
        
        Q = Q @ P
        A = P @ A

        if debug_print:
            print(f"p_{k + 1} = ", p)
            print(f"P_{k + 1} = ", P)
            print(f"P_{k + 1} @ A_{k - 1 + 1} = ", A)
            print()
        
        
        
 
    R = Q.T @ A_orig
        
    return Q, R

# Тестирование

In [269]:
def calc_solve(A: np.matrix, b: np.matrix) -> np.matrix:
    Q, R = qr(A)
    y = Q.T @ b
    x = np.linalg.solve(R, y)
    return x

## №1

In [270]:
A1 = np.matrix("1 2 3;"
               "4 6 7;"
               "8 9 0")
b1 = np.matrix("6;"
               "12;"
               "24")
x1 = np.matrix("-11.538;"
               "12.923;"
               "-2.769")

Q1, R1 = qr(A1)

C:\Users\artem\AppData\Local\Temp\ipykernel_17132\2403654919.py:35: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  P = np.eye(n) - 2 / float(sum(p[l] * p[l] for l in range(n))) * p * p.T


In [271]:
print("A = ", A1)
print("Q = ", Q1)
print("R = ", R1)
print("Q @ R = ", Q1 @ R1)

A =  [[1 2 3]
 [4 6 7]
 [8 9 0]]
Q =  [[-0.11111111 -0.50664569 -0.8549646 ]
 [-0.44444444 -0.74413586  0.49872935]
 [-0.88888889  0.43539864 -0.1424941 ]]
R =  [[-9.00000000e+00 -1.08888889e+01 -3.44444444e+00]
 [ 0.00000000e+00 -1.55951876e+00 -6.72888805e+00]
 [-2.22044605e-16  2.49800181e-16  9.26211650e-01]]
Q @ R =  [[1.00000000e+00 2.00000000e+00 3.00000000e+00]
 [4.00000000e+00 6.00000000e+00 7.00000000e+00]
 [8.00000000e+00 9.00000000e+00 7.85678349e-16]]


In [272]:
x1_r = calc_solve(A1, b1)
x1_r, x1_r - x1

C:\Users\artem\AppData\Local\Temp\ipykernel_17132\2403654919.py:35: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  P = np.eye(n) - 2 / float(sum(p[l] * p[l] for l in range(n))) * p * p.T


(matrix([[-11.53846154],
         [ 12.92307692],
         [ -2.76923077]]),
 matrix([[-4.61538462e-04],
         [ 7.69230769e-05],
         [-2.30769231e-04]]))

In [273]:
res = np.linalg.qr(A1)
A1, res.Q, res.R, res.Q @ res.R

(matrix([[1, 2, 3],
         [4, 6, 7],
         [8, 9, 0]]),
 matrix([[-0.11111111, -0.50664569, -0.8549646 ],
         [-0.44444444, -0.74413586,  0.49872935],
         [-0.88888889,  0.43539864, -0.1424941 ]]),
 matrix([[ -9.        , -10.88888889,  -3.44444444],
         [  0.        ,  -1.55951876,  -6.72888805],
         [  0.        ,   0.        ,   0.92621165]]),
 matrix([[1.00000000e+00, 2.00000000e+00, 3.00000000e+00],
         [4.00000000e+00, 6.00000000e+00, 7.00000000e+00],
         [8.00000000e+00, 9.00000000e+00, 9.41120157e-16]]))

## №2

In [274]:
A2= np.matrix("6.03 13 -17;"
              "13 29.03 -38;"
              "-17 -38 50.03")
b2 = np.matrix("2.0909;"
               "4.1509;"
               "-5.1191")
x2 = np.matrix("1.03;"
               "1.03;"
               "1.03")

Q2, R2 = qr(A2)

C:\Users\artem\AppData\Local\Temp\ipykernel_17132\2403654919.py:35: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  P = np.eye(n) - 2 / float(sum(p[l] * p[l] for l in range(n))) * p * p.T


In [275]:
print(A2)
print(Q2)
print(R2)
print(Q2 @ R2)


[[  6.03  13.   -17.  ]
 [ 13.    29.03 -38.  ]
 [-17.   -38.    50.03]]
[[-0.27120348  0.96131169 -0.04825465]
 [-0.58468412 -0.12471144  0.80161808]
 [ 0.76458692  0.24561534  0.59588585]]
[[-2.22342281e+01 -4.95533281e+01  6.50807391e+01]
 [-1.38777878e-16 -4.56704032e-01  6.84871421e-01]
 [ 1.88737914e-15  6.66133815e-16  1.71011233e-01]]
[[  6.03  13.   -17.  ]
 [ 13.    29.03 -38.  ]
 [-17.   -38.    50.03]]


In [276]:
res = np.linalg.qr(A2)
A2, res.Q, res.R, res.Q @ res.R

(matrix([[  6.03,  13.  , -17.  ],
         [ 13.  ,  29.03, -38.  ],
         [-17.  , -38.  ,  50.03]]),
 matrix([[-0.27120348,  0.96131169, -0.04825465],
         [-0.58468412, -0.12471144,  0.80161808],
         [ 0.76458692,  0.24561534,  0.59588585]]),
 matrix([[-22.23422812, -49.55332806,  65.08073913],
         [  0.        ,  -0.45670403,   0.68487142],
         [  0.        ,   0.        ,   0.17101123]]),
 matrix([[  6.03,  13.  , -17.  ],
         [ 13.  ,  29.03, -38.  ],
         [-17.  , -38.  ,  50.03]]))

In [277]:
x2_r = calc_solve(A2, b2)
x2_r, x2_r - x2

C:\Users\artem\AppData\Local\Temp\ipykernel_17132\2403654919.py:35: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  P = np.eye(n) - 2 / float(sum(p[l] * p[l] for l in range(n))) * p * p.T


(matrix([[1.03],
         [1.03],
         [1.03]]),
 matrix([[ 7.99360578e-15],
         [-3.48610030e-14],
         [-2.39808173e-14]]))

## №3 (СЛАУ)

In [278]:
A3 = np.matrix("2 0 1;"
               "0 1 -1;"
               "1 1 1")
b3 = np.matrix("3;"
               "0;"
               "3")

calc_solve(A3, b3)

C:\Users\artem\AppData\Local\Temp\ipykernel_17132\2403654919.py:35: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  P = np.eye(n) - 2 / float(sum(p[l] * p[l] for l in range(n))) * p * p.T


matrix([[1.],
        [1.],
        [1.]])