# Начало работы

In [20]:
import numpy as np

In [ ]:
def qr(A: np.matrix) -> tuple[np.matrix, np.matrix]:
    """
    QR метод через матрицы отражения

    Args:
        A (np.matrix): Матрица A

    Returns:
        (Q, R) (tuple[np.matrix, np.matrix]): Матрицы Q и R

    """
    
    n = A.shape[0]
    Q = np.eye(n)
    
    for k in range(n):
        # Вычисление нормали
        p = np.zeros((n, 1))
        a_kk = A[k, k]
        if a_kk != 0:
            a_kk_n = (1 if a_kk >= 0 else -1) * np.sqrt(sum(elem ** 2 for elem in A[k:, k]))
            
        else:
            a_kk_n = np.sqrt(2)
            
        p[k] = a_kk + a_kk_n
        p[k+1:] = A[k+1:, k]
        
        A[k,k]= a_kk_n
        A[k+1:, k]=0
        
        for j in range(k + 1, n):
            # print(np.vdot(p, p))
            old_a = A[:, j]
            m1 = sum(p[l] * old_a[l] for l in range(n))
            # m1 = np.dot(p, old_a)
            m2 = sum(p[l] * p[l] for l in range(n))
            # m2 = np.dot(p, p)
            dv = float(m1/m2)
            # print(m1, m2, dv, p)
            mult = 2 * dv * p
            A[:, j] = old_a - mult
        
        # print(p)
        # print(A)
        # print()
        
 
    R = Q.T @ A
        
    return Q, R

# Тестирование

In [105]:
A1 = np.matrix("1 2 3;"
               "4 6 7;"
               "8 9 0")
b1 = np.matrix("6;"
               "12;"
               "24")

Q1, R1 = qr(A1)
print()
print(Q1)
print(R1)
print(Q1 @ R1)



[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[  9. -10.  -3.]
 [  0.   1.  -6.]
 [  0.   0.   2.]]
[[  9. -10.  -3.]
 [  0.   1.  -6.]
 [  0.   0.   2.]]


C:\Users\artem\AppData\Local\Temp\ipykernel_17132\2515003761.py:29: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  A[k,k]= a_kk_n
C:\Users\artem\AppData\Local\Temp\ipykernel_17132\2515003761.py:39: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dv = float(m1/m2)


In [ ]:
A2= np.matrix("6.03 13 -17;"
              "13 29.03 -38;"
              "-17 -38 50.03")
b2 = np.matrix("2.0909;"
               "4.1509;"
               "-5.1191")

Q2, R2 = qr(A2)
print(Q2)
print(R2)
print(Q2 @ R2)

[[  0.]
 [ 13.]
 [-17.]]
[[  0.]
 [  0.]
 [-38.]]
[[0.]
 [0.]
 [0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[  6.03  13.   -17.  ]
 [ 13.    29.03 -38.  ]
 [-17.   -38.    50.03]]
[[  6.03  13.   -17.  ]
 [ 13.    29.03 -38.  ]
 [-17.   -38.    50.03]]
