В-18

18 % 5 = 3 => 4

In [260]:
import numpy as np
import numpy.linalg as LA

# Метод

In [261]:
def calc_LU(original: np.matrix) -> (np.matrix, np.matrix):
    matrixU = np.matrix(np.zeros(original.shape))
    matrixU[0] = original[0]

    matrixL = np.diag(np.ones((original.shape[0])))
    for i in range(original.shape[1]):
        matrixL[i, 0] = original[i, 0] / original[0, 0]

    for row in range(1, original.shape[0]):
        for column in range(1, original.shape[1]):
            if row <= column:
                elem_sum = sum(matrixL[row, i] * matrixU[i, column] for i in range(0, row - 1 + 1))
                matrixU[row, column] = original[row, column] - elem_sum
                continue
            elem_sum = sum(matrixL[row, i] * matrixU[i, column] for i in range(0, column - 1 + 1))
            matrixL[row, column] = (original[row, column] - elem_sum) / matrixU[column, column]
    return matrixL, matrixU

In [262]:
def solver(matrix, b):
    ML, MU = calc_LU(matrix)
    y = LA.solve(ML, b)
    x = LA.solve(MU, y)
    return x

# Проверка метода

In [263]:
mAt1 = np.matrix('2.1 -4.5 -2.0;'
                 '3.0 2.5 4.3;'
                 '-6.0 3.5 2.5')

vecbt1 = np.matrix('19.07;'
                   '3.21;'
                   '-18.25')

precise_res_t1 = np.matrix('1.34025;'
                           '-4.75798;'
                           '2.5771')
rest1 = solver(mAt1, vecbt1)
rest1, precise_res_t1 - rest1

(matrix([[ 1.34022645],
         [-4.75800672],
         [ 2.57775289]]),
 matrix([[ 2.35473435e-05],
         [ 2.67189250e-05],
         [-6.52892870e-04]]))

In [264]:
mAt2 = np.matrix('5 -1 5;'
                 '-3 6 2;'
                 '10 -7 0')

vecbt2 = np.matrix('3.2;'
                   '5.4;'
                   '-1.2')

precise_res_t2 = np.matrix('0.7297;'
                           '1.2138;'
                           '0.1531')
rest2 = solver(mAt2, vecbt2)
rest2, precise_res_t2 - rest2

(matrix([[0.72965517],
         [1.2137931 ],
         [0.15310345]]),
 matrix([[ 4.48275862e-05],
         [ 6.89655172e-06],
         [-3.44827586e-06]]))

In [265]:
mAt3 = np.matrix('5 2 3;'
                '1 6 1;'
                '3 -4 -2')

vecbt3 = np.matrix('3;'
                  '5;'
                  '8')

precise_res_t3 = np.matrix('2;'
                          '1;'
                          '-3')

rest3 = solver(mAt3, vecbt3)
rest3, precise_res_t3 - rest3

(matrix([[ 2.],
         [ 1.],
         [-3.]]),
 matrix([[-4.44089210e-16],
         [-2.22044605e-16],
         [ 4.44089210e-16]]))

In [266]:
matrixAt4 = [[1, 2, 1, 4],
             [2, 0, 4, 3],
             [4, 2, 2, 1],
             [-3, 1, 3, 2]]
matrixAt4 = np.matrix(matrixAt4)
vecbt4 = np.matrix('13;'
                   '28;'
                   '20;'
                   '6')
precise_res_t4 = np.matrix('3;'
                           '-1;'
                           '4;'
                           '2')

rest4 = solver(matrixAt4, vecbt4)
rest4, precise_res_t4 - rest4

(matrix([[ 3.],
         [-1.],
         [ 4.],
         [ 2.]]),
 matrix([[ 1.77635684e-15],
         [-5.77315973e-15],
         [ 8.88178420e-16],
         [ 4.44089210e-16]]))

In [267]:
mAt5 = np.matrix('2 1 3;'
                 '11 7 5;'
                 '9 8 4')

vecbt5 = np.matrix('1;'
                   '-6;'
                   '-5')

precise_res_t5 = np.matrix('-1;'
                           '0;'
                           '1')

rest5 = solver(mAt5, vecbt5)
rest5, precise_res_t5 - rest5

(matrix([[-1.],
         [ 0.],
         [ 1.]]),
 matrix([[-2.22044605e-16],
         [ 0.00000000e+00],
         [ 2.22044605e-16]]))

Как видим, всё хорошо!

# Решим уравнения

## №1

In [268]:
matA1 = np.matrix('13.14 -2.12 1.17;'
                  '-2.12 6.3 -2.45;'
                  '1.17 -2.45 4.6')
b1 = np.matrix('1.27;'
               '2.13;'
               '3.14')

res1 = solver(matA1, b1)
res1, matA1 @ res1

(matrix([[0.12996615],
         [0.80016894],
         [1.07572903]]),
 matrix([[1.27],
         [2.13],
         [3.14]]))

## №2

In [269]:
matA2 = np.matrix('4.31 0.26 0.61 0.27;'
                  '0.26 2.32 0.18 0.34;'
                  '0.61 0.18 3.2 0.31;'
                  '0.27 0.34 0.31 5.17')
b2 = np.matrix('1.02;'
               '1;'
               '1.34;'
               '1.27')

res2 = solver(matA2, b2)
res1, matA2 @ res2

(matrix([[0.12996615],
         [0.80016894],
         [1.07572903]]),
 matrix([[1.02],
         [1.  ],
         [1.34],
         [1.27]]))