In [63]:
import numpy as np
from numpy.linalg import solve

In [64]:
def holetskiy(original: np.matrix) -> np.matrix:
    matrixU = np.matrix(np.zeros(original.shape))
    matrixU[0, 0] = np.sqrt(original[0, 0])
    
    for i in range(1, original.shape[0]):
        matrixU[0, i] = original[0, 1] / matrixU[0, 0]
    
    for i in range(0, original.shape[0]):
        for j in range(0, original.shape[1]):
            if i == j:
                matrixU[i, j] = np.sqrt(original[i, j] - sum(matrixU[k, i] ** 2 for k in range(i - 1 + 1)))
            elif i < j:
                matrixU[i, j] = (original[i, j] - sum(matrixU[k, i] * matrixU[k, j] for k in range(i - 1 + 1))) / matrixU[i, i]
    return matrixU

In [65]:
def solution(matrix, b):
    hM = holetskiy(matrix)
    y = solve(hM.T, b)
    x = solve(hM, y)
    return x

# Тестовые номера

## №1

In [66]:
mA1 = np.matrix("81 -45 45;"
                "-45 50 -15;"
                "45 -15 38")
b1 = np.matrix("531;"
               "-460;"
               "193")
x1 = np.matrix("6;"
               "-5;"
               "-4")

x_c1 = solution(mA1, b1)
x_c1, x1 - x_c1

(matrix([[ 6.],
         [-5.],
         [-4.]]),
 matrix([[0.],
         [0.],
         [0.]]))

## №2

In [67]:
mA2 = np.matrix("6.25 -1 0.5;"
                "-1 5 2.12;"
                "0.5 2.12 3.6")
b2 = np.matrix("7.5;"
               "-8.68;"
               "-0.24")
x2 = np.matrix("0.8;"
               "-2;"
               "1")

x_c2 = solution(mA2, b2)
x_c2, x2 - x_c2

(matrix([[ 0.8],
         [-2. ],
         [ 1. ]]),
 matrix([[ 0.00000000e+00],
         [-4.44089210e-16],
         [ 2.22044605e-16]]))

## №3

Проблемы из-за того, что матрица не положительно-определённая

In [68]:
mA3 = np.matrix("1 3 -2 0 -2;"
                "3 4 -5 1 -3;"
                "-2 -5 3 -2 2;"
                "0 1 -2 5 3;"
                "-2 -3 2 3 4")
b3 = np.matrix("0.5;"
               "5.4;"
               "5.0;"
               "7.5;"
               "3.3")
x3 = np.matrix("-6.0978;"
               "-2.2016;"
               "-6.8011;"
               "-8.8996;"
               "0.1998")

x_c3 = solution(mA3, b3)
x_c3, x3 - x_c3

C:\Users\artem\AppData\Local\Temp\ipykernel_14484\560422138.py:11: RuntimeWarning: invalid value encountered in sqrt
  matrixU[i, j] = np.sqrt(original[i, j] - sum(matrixU[k, i] ** 2 for k in range(i - 1 + 1)))


(matrix([[nan],
         [nan],
         [nan],
         [nan],
         [nan]]),
 matrix([[nan],
         [nan],
         [nan],
         [nan],
         [nan]]))

## №4

In [69]:
mA4 = np.matrix("1 2 4;"
                "2 13 23;"
                "4 23 77")
b4 = np.matrix("10;"
               "50;"
               "150")
x4 = np.matrix("2.22;"
               "0.55;"
               "1.67")

x_c4 = solution(mA4, b4)
x_c4, x4 - x_c4

(matrix([[2.22222222],
         [0.55555556],
         [1.66666667]]),
 matrix([[-0.00222222],
         [-0.00555556],
         [ 0.00333333]]))

# СЛАУ

## №1

In [70]:
mA5 = np.matrix("5.9 0.3 -0.2;"
                "0.3 4 -0.7;"
                "-0.2 -0.7 6.7")
b5 = np.matrix("3.1;"
               "-1.7;"
               "1.1")

x_c5 = solution(mA5, b5)
x_c5

matrix([[ 0.55250081],
        [-0.44291815],
        [ 0.13439664]])

## №2

In [71]:
mA6 = np.matrix("4.12 0.42 1.34 0.88;"
                "0.42 3.95 1.87 0.43;"
                "1.34 1.87 3.2 0.31;"
                "0.88 0.43 0.31 5.17")
b6 = np.matrix("11.17;"
               "0.115;"
               "9.909;"
               "9.349")

x_c6 = solution(mA6, b6)
x_c6

matrix([[ 1.45653917],
        [-1.93309996],
        [ 3.46970779],
        [ 1.51312749]])