In [1]:
import numpy as np


In [4]:
def holetskiy(original: np.matrix) -> np.matrix:
    matrixU = np.matrix(np.zeros(original.shape))
    print(original)
    matrixU[0][0] = np.sqrt(original[0][0])
    
    for i in range(original.shape[0]):
        matrixU[0][i] = original[0][1] / matrixU[0][0]
    
    for i in range(0, original.shape[0]):
        for j in range(0, original.shape[1]):
            if i == j:
                matrixU[i][j] = np.sqrt(original[i][j] - sum(matrixU[k][i] for k in range(i - 1)))
            elif i < j:
                matrixU[i][j] = 1/matrixU[i][i] * (original[i][j] - sum(matrixU[k][i] * matrixU[k][j] for k in range(i - 1)))
    return matrixU

In [5]:
mA1 = np.matrix("81 -45 45;"
                "-45 50 -15;"
                "45 -15 38")
hA1 = holetskiy(mA1)
hA1

[[ 81 -45  45]
 [-45  50 -15]
 [ 45 -15  38]]


C:\Users\artem\AppData\Local\Temp\ipykernel_34636\3738220214.py:4: RuntimeWarning: invalid value encountered in sqrt
  matrixU[0][0] = np.sqrt(original[0][0])


IndexError: index 1 is out of bounds for axis 0 with size 1